apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: "{{ .Values.namespacename }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "prom/alertmanager:latest"
          ports:
            - containerPort: 9093
          args:
            - '--config.file=/config/config.yml'
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
