apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: {{ .Values.namespacename }}
data:
  config.yml: |
    {{ .Files.Get "monitoring/alertmanager/config.yml" | indent 4 }}
