apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: "{{ .Values.namespacename }}"
spec:
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
  type: ClusterIP
