apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: "{{ .Values.namespacename }}"
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.apiGateway.service.targetPort }}
          env:
            {{- range .Values.apiGateway.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
