apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: "{{ .Values.namespacename }}"
spec:
  selector:
    app: api-gateway
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}
      protocol: TCP
  type: {{ .Values.apiGateway.service.type }}
