apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: {{ .Values.namespacename }}
data:
  config.json: |-
{{ tpl (printf "{\n  \"PUBLIC_API_URL\": \"https://%s.student.k8s.aet.cit.tum.de/api\"\n}" .Values.namespacename) . | indent 4 }}

