apiVersion: v1
data:
  init-users.sql: |
    -- Insert 5 sample users
    -- IMPORTANT: Passwords are in plain text for this initial setup.

    CREATE TABLE IF NOT EXISTS app_user (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        name VARCHAR(255) NOT NULL
    );

    INSERT INTO app_user (email, password_hash, name) VALUES
    ('evtim@example.com', 'evtimpass', 'Evtim Kostadinov'),
    ('laura@example.com', 'laurapass', 'Laura Leschke'),
    ('carlos@example.com', 'carlospass', 'Carlos Mejia'),
    ('max@example.com', 'maxpass', 'Max Mustermann'),
    ('erika@example.com', 'erikapass', 'Erika Mustermann')
    ON CONFLICT (email) DO NOTHING; -- Optional: Prevents error if an email already exists, useful if script runs multiple times against a non-empty DB somehow, though initdb.d scripts usually don't.

    SELECT 'Finished initializing users from init-users.sql' AS status;
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-01T19:31:06Z"
  name: db-init-scripts
  namespace: team-lecture-bot
  resourceVersion: "12799318"
  uid: 13e780fe-09ae-445b-a70e-eee8d6fa1cb3
