apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: "{{ .Values.namespacename }}"
spec:
  selector:
    app: discovery-service
  ports:
    - port: {{ .Values.discoveryService.service.port }}
      targetPort: {{ .Values.discoveryService.service.targetPort }}
      protocol: TCP
  type: {{ .Values.discoveryService.service.type }}
