apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genai-backend-db-pvc
  namespace: "{{ .Values.namespacename }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
