apiVersion: v1
kind: Service
metadata:
  name: genai-backend-db
  namespace: "{{ .Values.namespacename }}"
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: genai-backend-db
