apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-backend-db
  namespace: "{{ .Values.namespacename }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-backend-db
  template:
    metadata:
      labels:
        app: genai-backend-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.genaiBackendDb.image.repository }}:{{ .Values.genaiBackendDb.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.genaiBackendDb.postgresDb }}"
            - name: POSTGRES_USER
              value: "{{ .Values.genaiBackendDb.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.genaiBackendDb.postgresPassword }}"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: genai-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: genai-db-data
          persistentVolumeClaim:
            claimName: genai-backend-db-pvc
