apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: "{{ .Values.namespacename }}"
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
