apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.namespacename }}
data:
  prometheus-datasource.yml: |
    {{ .Files.Get "monitoring/grafana/provisioning/datasources/prometheus-datasource.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ .Values.namespacename }}
data:
  dashboards.yml: |
    {{ .Files.Get "monitoring/grafana/provisioning/dashboards/dashboards.yml" | indent 4 }}
  service-health-dashboard.json: |
    {{ .Files.Get "monitoring/grafana/provisioning/dashboards/service-health-dashboard.json" | indent 4 }}
  lecturebot-dashboard.json: |
    {{ .Files.Get "monitoring/grafana/provisioning/dashboards/lecturebot-dashboard.json" | indent 4 }}
