{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "lecture-bot-ingress"
  namespace: "{{ .Values.namespacename }}"
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.namespacename }}.student.k8s.aet.cit.tum.de"
      secretName: "lecture-bot-devops25-tls"
  {{- end }}
  rules:
    - host: "{{ .Values.namespacename }}.student.k8s.aet.cit.tum.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: {{ .Values.apiGateway.service.port }}
{{- end }}
