apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: {{ .Values.namespacename }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi 
