apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture-bot-server
  namespace: "{{ .Values.namespacename }}"
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: lecture-bot-server-selector
  template:
    metadata:
      labels:
        app: lecture-bot-server-selector
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh 
            - -c 
            - > 
              until nc -z {{ .Values.dbServiceName | default "lecturebot-db" }} {{ .Values.db.service.port }};
              do
                echo waiting for db;
                sleep 3;
              done
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: {{ .Values.server.service.targetPort }}
          env:
            {{- range .Values.server.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
