apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: "{{ .Values.namespacename }}"
spec:
  selector:
    app: lecture-bot-server-selector
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
  type: {{ .Values.server.service.type }}
