apiVersion: v1
kind: Service
metadata:
  name: user-course-microservice
  namespace: "{{ .Values.namespacename }}"
spec:
  selector:
    app: user-course-microservice
  ports:
    - port: {{ .Values.userCourseMicroservice.service.port }}
      targetPort: {{ .Values.userCourseMicroservice.service.targetPort }}
      protocol: TCP
  type: {{ .Values.userCourseMicroservice.service.type }}
