apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: "{{ .Values.namespacename }}"
spec:
  selector:
    app: weaviate
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
  type: {{ .Values.weaviate.service.type }}
