# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff
        name: ruff (linter)
        args: [--fix, --exit-non-zero-on-fix]
        # Run only on python files in the genai service
        files: ^services/genai/.*\.py$
    -   id: ruff-format
        name: ruff (formatter)
        # Run only on python files in the genai service
        files: ^services/genai/.*\.py$

-   repo: local
    hooks:
    -   id: pytest-genai
        name: Run genai service tests
        entry: bash -c 'cd services/genai && PYTHONPATH=src poetry run pytest'
        language: system
        types: [python]
        pass_filenames: false
        files: ^services/genai/