version: '3.8'

services:
  reverse-proxy:
    image: traefik:v3.4
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@tum.de"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - lecturebot-net

  lecturebot-db:
    image: postgres:16
    environment:
      POSTGRES_DB: lecturebot_db
      POSTGRES_USER: lecturebot_user
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - lecturebot_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lecturebot_user -d lecturebot_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - lecturebot-net

  server:
    image: ghcr.io/aet-devops25/team-lecture-bot/server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lecturebot-db:5432/lecturebot_db
      - SPRING_DATASOURCE_USERNAME=lecturebot_user
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - LECTUREBOT_CLIENT_ORIGIN_PORT_3000=http://client.${SERVER_HOST}
      - LECTUREBOT_CLIENT_ORIGIN_PORT_5173=http://localhost:5173
    restart: unless-stopped
    depends_on:
      lecturebot-db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`${SERVER_HOST}`)"
      - "traefik.http.services.server.loadbalancer.server.port=8080"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=letsencrypt"
    networks:
      - lecturebot-net

  client:
    image: ghcr.io/aet-devops25/team-lecture-bot/client:latest
    environment:
      - PUBLIC_API_URL=https://api.${SERVER_HOST}/api
    depends_on:
      - server
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`${CLIENT_HOST}`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.client-compress.compress=true"
      - "traefik.http.routers.client.middlewares=client-compress"
      - "traefik.http.routers.client.priority=1"
    networks:
      - lecturebot-net

volumes:
  lecturebot_db_data:

networks:
  lecturebot-net:
    driver: bridge

