version: '3.8'

services:
  lecturebot-db:
    image: postgres:16
    container_name: lecturebot-postgres-db
    environment:
      POSTGRES_DB: lecturebot_db
      POSTGRES_USER: lecturebot_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - lecturebot_db_data:/var/lib/postgresql/data
      - ./server/db-init:/docker-entrypoint-initdb.d
    networks:
      - lecturebot-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lecturebot_user -d lecturebot_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  lecturebot-server:
    build: ./server
    container_name: lecturebot-app-server
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lecturebot-db:5432/lecturebot_db
      - SPRING_DATASOURCE_USERNAME=lecturebot_user
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      lecturebot-db:
        condition: service_healthy
    networks:
      - lecturebot-net
    restart: unless-stopped

  lecturebot-client:
    build: ./client
    container_name: lecturebot-app-client
    ports:
      - "3000:3000"
    networks:
      - lecturebot-net
    depends_on:
      - lecturebot-server
    restart: unless-stopped

volumes:
  lecturebot_db_data:

networks:
  lecturebot-net:
    driver: bridge
