namespace:
  create: false

namespacename: team-lecture-bot

global:
  image:
    tag: task-monitoring-and-observability 

client:
  publicApiUrl: https://{{ .Values.namespacename }}.student.k8s.aet.cit.tum.de/api/v1
  image:
    repository: ghcr.io/aet-devops25/team-lecture-bot/client
    #tag: {{ .Values.global.image.tag }}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  replicaCount: 1
  env:
    - name: PUBLIC_API_URL
      value: https://{{ .Values.namespacename }}.student.k8s.aet.cit.tum.de/api/v1
    - name: VITE_API_BASE_URL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: PUBLIC_API_URL


apiGateway:
  image:
    repository: ghcr.io/aet-devops25/team-lecture-bot/api-gateway
    #tag: {{ .Values.global.image.tag }}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: api-gateway
    - name: SERVER_PORT
      value: 8080
    - name: EUREKA_URI
      value: http://discovery-service:8761/eureka/
    - name: LECTUREBOT_CLIENT_ORIGIN
      value: https://{{ .Values.namespacename }}.student.k8s.aet.cit.tum.de
    - name: app.jwtSecret
      value: c29tZXRoaW5nLXNlY3JldC1mb3ItbGVjdHVyZS1ib3QtYXBwbGljYXRpb24tMjAyNC1kZXZvcHM=
    - name: app.jwtExpirationInMs
      value: "86400000" # 24 hours

userCourseMicroservice:
  image:
    repository: ghcr.io/aet-devops25/team-lecture-bot/user-course-microservice
    #tag: {{ .Values.global.image.tag }}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  replicaCount: 1
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: user-course-microservice
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://lecturebot-db:5432/lecturebot_db
    - name: SPRING_DATASOURCE_USERNAME
      value: lecturebot_user
    - name: SPRING_DATASOURCE_PASSWORD
      value: mysecretpassword
    - name: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - name: GENAI_SERVICE_BASE_URL
      value: http://genai-service:8011
    - name: LECTUREBOT_CLIENT_ORIGIN
      value: https://{{ .Values.namespacename }}.student.k8s.aet.cit.tum.de
    - name: app.jwtSecret
      value: c29tZXRoaW5nLXNlY3JldC1mb3ItbGVjdHVyZS1ib3QtYXBwbGljYXRpb24tMjAyNC1kZXZvcHM=
    - name: app.jwtExpirationInMs
      value: "86400000" # 24 hours
    - name: EUREKA_URI
      value: http://discovery-service:8761/eureka/

genaiBackendMicroservice:
  image:
    repository: ghcr.io/aet-devops25/team-lecture-bot/genai-backend-microservice
    #tag: {{ .Values.global.image.tag }}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8082
    targetPort: 8082
  replicaCount: 1
  env:
    - name: EUREKA_INSTANCE_HOSTNAME
      value: genai-backend-microservice
    - name: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: update
    - name: SPRING_DATASOURCE_URL
      value: jdbc:postgresql://genai-backend-db:5432/genai_db
    - name: SPRING_DATASOURCE_USERNAME
      value: genai_user
    - name: SPRING_DATASOURCE_PASSWORD
      value: mysecretpassword
    - name: GENAI_SERVICE_BASE_URL
      value: http://genai-service:8011
    - name: app.jwtSecret
      value: c29tZXRoaW5nLXNlY3JldC1mb3ItbGVjdHVyZS1ib3QtYXBwbGljYXRpb24tMjAyNC1kZXZvcHM=
    - name: app.jwtExpirationInMs
      value: "86400000" # 24 hours
    - name: EUREKA_URI
      value: http://discovery-service:8761/eureka/


discoveryService:
  image:
    repository: ghcr.io/aet-devops25/team-lecture-bot/discovery-service
    #tag: {{ .Values.global.image.tag }}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8761
    targetPort: 8761
  replicaCount: 1
  env:
    - name: app.jwtSecret
      value: c29tZXRoaW5nLXNlY3JldC1mb3ItbGVjdHVyZS1ib3QtYXBwbGljYXRpb24tMjAyNC1kZXZvcHM=
    - name: app.jwtExpirationInMs
      value: "86400000" # 24 hours



genaiService:
  image:
    repository: ghcr.io/aet-devops25/team-lecture-bot/genai
    #tag: {{ .Values.global.image.tag }}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8011
    targetPort: 8011
  replicaCount: 1
  env:
    - name: LLM_PROVIDER
      value: "tum_aet"
    - name: OLLAMA_MODEL_NAME
      value: "llama3:8b-instruct-q4_K_M"
    - name: OLLAMA_BASE_URL
      value: "http://host.docker.internal:11434"
    - name: OPENAI_API_KEY
      value: "your_openai_key_if_using_openai"
    - name: OPENAI_MODEL_NAME
      value: "gpt-4o-mini"
    - name: TUM_AET_LLM_API_BASE
      value: "https://gpu.aet.cit.tum.de/api"
    - name: TUM_AET_LLM_API_KEY
      value: "sk-d56891f96ed94add810873324af99ef0"
    - name: TUM_AET_LLM_MODEL_NAME
      value: "llama3.3:latest"
    - name: WEAVIATE_URL
      value: "http://weaviate:8080"
    - name: TOKENIZERS_PARALLELISM
      value: "false"

weaviate:
  image:
    repository: semitechnologies/weaviate
    tag: latest 
    #tag: {{ .Values.global.image.tag }}
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  replicaCount: 1
  env:
    - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
      value: true
    - name: PERSISTENCE_DATA_PATH
      value: /var/lib/weaviate
    - name: DEFAULT_VECTORIZER_MODULE
      value: "none"
    - name: ENABLE_MODULES
      value: ""
    - name: CLUSTER_HOSTNAME
      value: "node1"



dbServiceName: lecturebot-db

db:
  postgresDb: lecturebot_db
  postgresUser: lecturebot_user
  postgresPassword: mysecretpassword
  image:
    repository: postgres
    tag: 16
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432

genaiBackendDb:
  postgresDb: genai_db
  postgresUser: genai_user
  postgresPassword: mysecretpassword
  image:
    repository: postgres
    tag: 16
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432


ingress:
  enabled: true
  className: nginx
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
