server:
  port: 8080

spring:
  application:
    # It's good practice to name your gateway application
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for the User & Authentication Microservice
        - id: user_course_microservice_route
          uri: lb://user-course-microservice
          predicates:
            # The full path, including the base, is matched here
            - Path=/api/v1/profile/**, /api/v1/coursespaces/**, /api/v1/auth/**
          filters:
            # This filter strips the '/api/v1' part before forwarding
            - StripPrefix=2

        # Route for the Flashcard QA Microservice
        - id: genai_backend_microservice_route 
          uri: lb://genai-backend-microservice
          predicates:
            - Path=/api/v1/genai/**
          filters:
            - StripPrefix=2

# --- Actuator info ---
management:
  endpoints:
    web:
      exposure:
        # Expose specific endpoints. 'health' and 'info' are safe.
        # 'prometheus' is for metrics scraping. Add others as needed.
        include: health,info,prometheus
  endpoint:
    health:
      # This setting shows full details (like disk space, db connection, etc.)
      # in the /actuator/health response. Very useful for debugging.
      show-details: always
      # Configuration for readiness and liveness probes in k8s
      probes:
        enabled: true

# --- Eureka Client Configuration ---
eureka:
  instance:
    hostname: api-gateway
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-user:eureka-password@localhost:8761/eureka/}

# --- Custom Application Properties (JWT Configuration) ---
app:
  jwt:
    # IMPORTANT: The secret should be a long, random, base64-encoded string and kept secure.
    # You can generate a new one for production using: openssl rand -base64 32
    secret: c29tZXRoaW5nLXNlY3JldC1mb3ItbGVjdHVyZS1ib3QtYXBwbGljYXRpb24tMjAyNC1kZXZvcHM=
    # Token expiration in milliseconds (e.g., 86400000 for 24 hours)
    expirationInMs: 86400000

