server:
  port: 8082

spring:
  application:
    name: genai-backend-microservice


#spring:
#  mvc:
#    servlet:
#      path: /api/v1
#
eureka:
  instance:
    # The hostname for the Eureka instance. This is used for service discovery.
    hostname: genai-backend-microservice
    # Use IP address instead of hostname for registration
    prefer-ip-address: false
  client:
    service-url:
      # Use a placeholder ${EUREKA_URI}.
      # If the variable isn't set, it will default to the value after the colon (:).
      defaultZone: ${EUREKA_URI:http://eureka-user:eureka-password@localhost:8761/eureka/}



# --- Actuator Info ---
management:
  endpoints:
    web:
      exposure:
        # Expose specific endpoints. 'health' and 'info' are safe.
        # 'prometheus' is for metrics scraping. Add others as needed.
        include: health,info,prometheus
  endpoint:
    health:
      # This setting shows full details (like disk space, db connection, etc.)
      # in the /actuator/health response. Very useful for debugging.
      show-details: always
      # Configuration for readiness and liveness probes in k8s
      probes:
        enabled: true
# JWT Configuration
# IMPORTANT: The secret should be a long, random, base64-encoded string and kept secure.
# You can generate a new one for production using: openssl rand -base64 32
app:
  jwtSecret: c29tZXRoaW5nLXNlY3JldC1mb3ItbGVjdHVyZS1ib3QtYXBwbGljYXRpb24tMjAyNC1kZXZvcHM=
# Token expiration in milliseconds (e.g., 86400000 for 24 hours)
  jwtExpirationInMs: 86400000
