global:
  scrape_interval: 15s

rule_files:
  - 'alert.rules.yaml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'

scrape_configs:
  - job_name: 'user-course-microservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-course-microservice:8081']
        labels:
          application: 'user-course-microservice'

  - job_name: 'genai-backend-microservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['genai-backend-microservice:8082']
        labels:
          application: 'genai-backend-microservice'

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'api-gateway'

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-service:8761']
        labels:
          application: 'discovery-service'
    basic_auth:
      username: 'eureka-user'
      password: 'eureka-password'

  - job_name: 'genai-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai-service:8011']
        labels:
          application: 'genai-service'


