openapi: 3.0.3
info:
  title: LECture-bot API
  description: The official API for the LECture-bot application.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
paths:
  /health:
    get:
      summary: Health Check
      description: Checks if the server is running.
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Server is up and running.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
  /auth/register:
    post:
      summary: Register a new user
      description: Creates a new user account.
      operationId: registerUser
      tags:
        - Authentication
      requestBody:
        description: User registration details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Registration successful.
          content:
            text/plain:
              schema:
                type: string
                example: Registration successful for user@example.com
        '400':
          description: Bad Request - Invalid input or email already exists.
          content:
            text/plain:
              schema:
                type: string
                example: Email already exists
  /auth/login:
    post:
      summary: Log in a user
      description: Authenticates a user and returns a JWT.
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        description: User login credentials
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized - Bad credentials.

components:
  schemas:
    HealthStatus:
      type: object
      properties:
        status:
          type: string
          example: UP
        message:
          type: string
          example: LECture-bot server is running!
    RegisterRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: Ada Lovelace
        email:
          type: string
          format: email
          example: ada.lovelace@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: Password123!
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: ada.lovelace@example.com
        password:
          type: string
          format: password
          example: Password123!
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZGEubG92ZWxhY2VAZXhhbXBsZS5jb20iLCJpYXQiOjE2MTYyMzkwMjIsImV4cCI6MTYxNjMyNTQyMn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c